/*
 * Fenix Planner
 * Copyright (C) 2013 Petter Holmström
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.github.peholmst.fenix.planner.ui;

import com.github.peholmst.fenix.planner.ApplicationInfo;
import com.github.peholmst.fenix.planner.model.Program;
import com.github.peholmst.fenix.planner.ui.actions.EditOrganizersAction;
import com.github.peholmst.fenix.planner.ui.actions.QuitAction;

/**
 *
 * @author peholmst
 */
public class MainFrame extends javax.swing.JFrame {

    private final QuitAction quit;
    private final EditOrganizersAction editOrganizers;
    
    private final Program program;
    
    public MainFrame(Program program) {
        this.program = program;
        quit = new QuitAction();
        editOrganizers = new EditOrganizersAction(this, program);
        setTitle(ApplicationInfo.getTitle());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        documentMenu = new javax.swing.JMenu();
        quitMenuItem = new javax.swing.JMenuItem();
        programMenu = new javax.swing.JMenu();
        editOrganizersItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        documentMenu.setMnemonic('D');
        documentMenu.setText("Dokument");

        quitMenuItem.setAction(quit);
        documentMenu.add(quitMenuItem);

        jMenuBar1.add(documentMenu);

        programMenu.setMnemonic('P');
        programMenu.setText("Program");

        editOrganizersItem.setAction(editOrganizers);
        programMenu.add(editOrganizersItem);

        jMenuItem2.setText("Händelsetyper");
        programMenu.add(jMenuItem2);

        jMenuBar1.add(programMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu documentMenu;
    private javax.swing.JMenuItem editOrganizersItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu programMenu;
    private javax.swing.JMenuItem quitMenuItem;
    // End of variables declaration//GEN-END:variables
}
